kind: PersistentVolume
apiVersion: v1
metadata:
  name: connect2
  labels:
    type: local
spec:
  storageClassName: connect2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kafka/connect/connect-2"
