kind: PersistentVolume
apiVersion: v1
metadata:
  name: connect1
  labels:
    type: local
spec:
  storageClassName: connect1
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kafka/connect/connect-1"
