kind: PersistentVolume
apiVersion: v1
metadata:
  name: connect0
  labels:
    type: local
spec:
  storageClassName: connect0
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kafka/connect/connect-0"
