kind: PersistentVolume
apiVersion: v1
metadata:
  name: zk1
  labels:
    type: local
spec:
  storageClassName: zk1
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kafka/zookeeper/zk-1"
