kind: PersistentVolume
apiVersion: v1
metadata:
  name: zk2
  labels:
    type: local
spec:
  storageClassName: zk2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kafka/zookeeper/zk-2"
