kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka0
  labels:
    type: local
spec:
  storageClassName: kafka0
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kafka/kafka/kafka-0"
